### ISSUE TITLE
Incompatible with version 51.3?

### ISSUE THREAD

**Issue by marbaque** [Iconscout/icondrop#1]
I tried to use this but I always get the message:

> Please select a layer with a single rectangular shape

I am doing exactly that. I might think that it is not compatible with the version of my sketch.

**Comment by tarunmangukiya** [comment]
Thanks for reporting the issue @marbaque.

Let me go into the details of it and will revert you back. Any specific steps you followed that can help in debugging?

**Comment by tarunmangukiya** [comment]
Hi @marbaque,

We've updated the sketch plugin which supports the latest Sketch update. Can you try it out?
